#!/usr/bin/env bash

### Helpers functions

test::helpers::get_php_version() {
    local old_home

    old_home="${HOME}"

    HOME="/app"
    export HOME

    pushd "${HOME}" > /dev/null

    cp --archive --recursive "${BUILD_DIR}"/* "${HOME}/"

    test::utils::capture ./vendor/php/bin/php --version

    popd > /dev/null

    rm -Rf "${HOME}"/*

    HOME="${old_home}"
    export HOME
}
