#!/usr/bin/env bash

readonly default_builtins_extensions_82=(
	"bcmath" "bz2" "Core" "ctype" "curl" "date" "dom" "exif" "fileinfo"
	"filter" "gd" "hash" "iconv" "intl" "json" "libxml" "mbstring" "mysqli"
	"mysqlnd" "openssl" "pcntl" "pcre" "PDO" "pdo_mysql" "pdo_pgsql"
	"pdo_sqlite" "pgsql" "Phar" "posix" "random" "readline" "Reflection"
	"session" "shmop" "SimpleXML" "soap" "sockets" "SPL" "sqlite3" "standard"
	"tokenizer" "xml" "xmlreader" "xmlwriter" "xsl" "Zend OPcache" "zip" "zlib"
)

readonly default_pecl_extensions_82=(
	"apcu" "mongodb" "redis"
)

readonly optional_builtin_extensions_82=(
	"calendar" "ftp" "gettext" "gmp" "imap" "sodium" "tidy"
)

test::php82::classic() {
#
# Test a deployment of a classic app (not using Composer)
# Specifying we want PHP 8.2.x via environment
#

	PHP_VERSION="8.2"
	export PHP_VERSION

	test::utils::setupFixture "defaults/classic"
	test::helpers::classic_deploy \
		"8.2." \
		"${default_nginx["${STACK}"]}"
}

test::php82::composer() {
#
# Test a deployment of a PHP app using Composer
# Specifying we want PHP 8.2.x via composer.json
#

	test::utils::setupFixture "php-8.2/composer"
	test::helpers::composer_deploy \
		"8.2." \
		"${default_nginx["${STACK}"]}" \
		"${default_composer["${STACK}"]}"
}

test::php82::extensions::default() {
#
# Test the presence of default enabled built-in extensions.
#

	test::utils::setupFixture "php-8.2/composer"

	test::utils::compile
	test::helpers::enter_prod

	local extensions=("${default_builtin_extensions_82[@]}")
	extensions+=("${default_pecl_extensions_82[@]}")

	test::helpers::enabled_extensions "${extensions[@]}"
}

test::php82::extensions::optional_builtin() {
#
# Test the presence of available built-in extensions that are not
# enabled by default.
#

	test::utils::setupFixture "php-8.2/optional_builtin"

	test::utils::compile
	test::helpers::enter_prod

	test::helpers::enabled_extensions "${optional_builtin_extensions_82[@]}"
}
