#!/usr/bin/env bash

source "$( pwd )/test/utils"
source "$( pwd )/test/helpers"

# List of modules that we want to ship with every PHP setup.
# For now, users can't specify a version for these modules, we just ship
# what we have. Hence no specific versions constraints here.
readonly default_modules=(
    "apcu" "bcmath" "bz2" "Core" "ctype" "curl" "date" "dom" "exif" "fileinfo"
    "filter" "gd" "hash" "iconv" "intl" "json" "libxml" "mbstring" "mongodb"
    "mysqli" "mysqlnd" "openssl" "pcntl" "pcre" "PDO" "pdo_mysql" "pdo_pgsql"
    "pdo_sqlite" "pgsql" "Phar" "posix" "readline" "redis" "Reflection"
    "session" "shmop" "SimpleXML" "soap" "sockets" "SPL" "sqlite3" "standard"
    "tokenizer" "xml" "xmlreader" "xmlwriter" "xsl" "Zend OPcache" "zip" "zlib"
)


test::legacy::defaults() {
    # Test a deployment of a legacy app (not using Composer)
    # With default settings

    test::helpers::test_deploy "legacy_default" "PHP (classic)" "8.1."
}

test::legacy::php80() {
    # Test a deployment of a legacy app (not using Composer)
    # Specifying we want PHP 8.0.x via environment

    PHP_VERSION="8.0"
    export PHP_VERSION

    # PHP 8.0 is only available on stack `scalingo-20`:
    if [[ "${STACK}" != "scalingo-20" ]]; then
        echo "[skipping] PHP 8.0 is not available on scalingo-22"
        startSkipping
    fi

    test::helpers::test_deploy "legacy_default" "PHP (classic)" "8.0."
}

test::legacy::php81() {
    # Test a deployment of a legacy app (not using Composer)
    # Specifying we want PHP 8.1.x via environment

    PHP_VERSION="8.1"
    export PHP_VERSION

    test::helpers::test_deploy "legacy_default" "PHP (classic)" "8.1."
}

test::legacy::php82() {
    # Test a deployment of a legacy app (not using Composer)
    # Specifying we want PHP 8.2.x via environment

    PHP_VERSION="8.2"
    export PHP_VERSION

    test::helpers::test_deploy "legacy_default" "PHP (classic)" "8.2."
}

test::legacy::php83() {
    # Test a deployment of a legacy app (not using Composer)
    # Specifying we want PHP 8.3.x via environment

    PHP_VERSION="8.3"
    export PHP_VERSION

    test::helpers::test_deploy "legacy_default" "PHP (classic)" "8.3."
}

test::composer::defaults() {
    # Test a deployment of a PHP app using Composer
    # With default settings

    test::helpers::test_deploy "composer_default" "PHP (composer.json)" "8.1."
}

test::composer::php80() {
    # Test a deployment of a PHP app using Composer
    # Specifying we want PHP 8.0.x in composer.json

    # PHP 8.0 is only available on stack `scalingo-20`:
    if [[ "${STACK}" != "scalingo-20" ]]; then
        echo "[skipping] PHP 8.0 is not available on scalingo-22"
        startSkipping
    fi

    test::helpers::test_deploy "composer_php80" "PHP (composer.json)" "8.0."
}

test::composer::php81() {
    # Test a deployment of a PHP app using Composer
    # Specifying we want PHP 8.1.x in composer.json

    test::helpers::test_deploy "composer_php81" "PHP (composer.json)" "8.1."
}

test::composer::php82() {
    # Test a deployment of a PHP app using Composer
    # Specifying we want PHP 8.2.x in composer.json

    test::helpers::test_deploy "composer_php82" "PHP (composer.json)" "8.2."
}

test::composer::php83() {
    # Test a deployment of a PHP app using Composer
    # Specifying we want PHP 8.3.x in composer.json

    test::helpers::test_deploy "composer_php83" "PHP (composer.json)" "8.3."
}


# Add these functions to the test suite:

suite_addTest test::legacy::defaults
suite_addTest test::legacy::php80
suite_addTest test::legacy::php81
suite_addTest test::legacy::php82
suite_addTest test::legacy::php83

suite_addTest test::composer::defaults
suite_addTest test::composer::php80
suite_addTest test::composer::php81
suite_addTest test::composer::php82
suite_addTest test::composer::php83
