#!/usr/bin/env bash

set -e

mcrypt_version="$1"

if [ -z "$mcrypt_version" ]; then
    echo "Usage: $(basename "$0") VERSION" >&2
    exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"
source "$basedir/lib/utils"
source "$basedir/lib/swift"

export PATH=${basedir}/../vendor/bin:$PATH

tempdir=$(mktmpdir libmcrypt)
cd $tempdir

echo "-----> Downloading libmcrypt ${mcrypt_version}"
curl -L "http://sourceforge.net/projects/mcrypt/files/Libmcrypt/${mcrypt_version}/libmcrypt-${mcrypt_version}.tar.gz/download" \
    | tar xzv

mkdir -p /app/vendor/libmcrypt \
  && pushd libmcrypt-${mcrypt_version} > /dev/null \
  && ./configure --disable-posix-threads --prefix=/app/vendor/libmcrypt \
  && make && make install \
  && popd > /dev/null

mkdir package
pushd /app/vendor/libmcrypt > /dev/null
tar zcvf "${tempdir}/package/libmcrypt-${mcrypt_version}.tgz" .
popd > /dev/null

swift_upload package/libmcrypt-${mcrypt_version}.tgz

"$basedir/package-checksum" "libmcrypt-${mcrypt_version}"
