#!/usr/bin/env bash

set -e

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# The variable is assigned in `buildpack.conf`
declare sodium_version
source "$basedir/../conf/buildpack.conf"
source "$basedir/lib/utils"
source "$basedir/lib/swift"

function build_libsodium() {
  version="${1}"
  url_prefix="${2}"

  rm --recursive --force /app/vendor/libsodium
  mkdir --parents /app/vendor/libsodium

  tempdir="$( mktmpdir libsodium )"
  pushd "${tempdir}"

  echo "-----> Downloading Sodium v${version}"
  curl --fail --location --remote-name "https://download.libsodium.org/libsodium/${url_prefix}/libsodium-${version}.tar.gz"

  mkdir "libsodium"
  pushd "libsodium"

  tar --extract --verbose --strip-components=1 \
      --file="../libsodium-${version}.tar.gz"

  ./configure --prefix=/app/vendor/libsodium
  make
  make install

  popd

  mkdir "package"
  pushd "package"

  tar --directory="/app/vendor/libsodium" --create --gzip --verbose \
      --file="libsodium-${version}.tgz" .

  popd

  swift_upload "package/libsodium-${version}.tgz"
  "${basedir}/package-checksum" "libsodium-${version}"

  popd
}

build_libsodium "$sodium_version" "releases"
