#!/usr/bin/env bash

set -e
if [ -n "$DEBUG" ]; then
  set -x
fi

zlib_version="$1"
basedir="$( cd -P "$( dirname "$0" )" && pwd )"

source "$basedir/../conf/versions.sh"
source "$basedir/lib/utils"
source "$basedir/lib/swift"

tempdir=$(mktmpdir zlib)
cd "$tempdir"

echo "-----> Downloading ZLib v${zlib_version}"
curl --fail --location --remote-name "https://zlib.net/zlib-${zlib_version}.tar.gz"

mkdir zlib
mv "zlib-${zlib_version}.tar.gz" zlib

swift_upload "zlib/zlib-${zlib_version}.tar.gz"
