#!/usr/bin/env bash

zlib_version="$1"
basedir="$( cd -P "$( dirname "$0" )" && pwd )"

source "$basedir/../conf/buildpack.conf"
source "$basedir/utils"
source "$basedir/swift"

tempdir=$(mktmpdir zlib)
cd $tempdir

echo "-----> Downloading ZLib v${zlib_version}"
curl -LO "http://zlib.net/zlib-${zlib_version}.tar.gz"

mkdir zlib
mv zlib-${zlib_version}.tar.gz zlib

swift_upload "zlib/zlib-${zlib_version}.tar.gz"
