#!/usr/bin/env bash

set -e
if [ -n "$DEBUG" ]; then
  set -x
fi

which m4 2> /dev/null || (apt-get update && apt-get install --yes m4)

# The variable is assigned in `versions.sh`
declare gmp_version
basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/versions.sh"
source "$basedir/lib/utils"
source "$basedir/lib/swift"

export PATH=${basedir}/../vendor/bin:$PATH

tempdir=$(mktmpdir gmp)
cd "$tempdir"

echo "-----> Downloading gmp ${gmp_version}"
curl --fail --location "https://gmplib.org/download/gmp/gmp-${gmp_version}.tar.xz" \
  | tar xJv

mkdir -p /app/vendor/gmp
pushd "gmp-${gmp_version}" > /dev/null
# We need the `CC` flag since gcc v15 (used in scalingo-26).
# gcc v15 default C mode changed to C23 which made the configuration fails. A fix is already written but not yet published. Hence the `CC` flag may be deleted in the next releases.
./configure --prefix=/app/vendor/gmp CC="gcc -std=gnu17"
make
make check
make install
popd > /dev/null

mkdir package
pushd /app/vendor/gmp > /dev/null
tar zcvf "${tempdir}/package/gmp-${gmp_version}.tgz" .
popd > /dev/null

swift_upload "package/gmp-${gmp_version}.tgz"

"$basedir/package-checksum" "gmp-${gmp_version}"
