#!/usr/bin/env bash

lua_version="$1"
basedir="$( cd -P "$( dirname "$0" )" && pwd )"

source "$basedir/../conf/buildpack.conf"
source "$basedir/lib/utils"
source "$basedir/lib/swift"

tempdir=$(mktmpdir lua)
cd $tempdir

echo "-----> Downloading Lua v${lua_version}"
curl -LO "https://www.lua.org/ftp/lua-${lua_version}.tar.gz"

tar xvf "lua-${lua_version}.tar.gz"
cd "lua-${lua_version}"

make linux local MYCFLAGS=-fPIC

rm -rf /app/vendor/lua
mv install /app/vendor/lua

cd $tempdir
mkdir package
cd package
tar -C /app/vendor/lua -czvf "lua-${lua_version}.tgz" .
cd ..

swift_upload package/lua-${lua_version}.tgz

"$basedir/package-checksum" "lua-${lua_version}" 
