#!/usr/bin/env bash

set -e
if [ -n "$DEBUG" ]; then
  set -x
fi

webp_version="$1"

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

source "$basedir/../conf/versions.sh"
source "$basedir/lib/utils"
source "$basedir/lib/swift"

tempdir=$(mktmpdir webp)
cd "$tempdir"

echo "-----> Downloading WebP v${webp_version}"
curl --fail --location --output - "https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-${webp_version}.tar.gz"| tar xzv

mkdir -p /app/vendor/libwebp
pushd "libwebp-${webp_version}" > /dev/null
./configure --prefix=/app/vendor/libwebp
make
make install
popd > /dev/null

mkdir package
pushd /app/vendor/libwebp > /dev/null
tar zcvf "${tempdir}/package/libwebp-${webp_version}.tgz" .
popd > /dev/null

swift_upload "package/libwebp-${webp_version}.tgz"

"$basedir/package-checksum" "libwebp-${webp_version}"
