#!/usr/bin/env bash

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"
source "$basedir/lib/utils"
source "$basedir/lib/swift"

tempdir=$(mktmpdir composer)
cd $tempdir

curl -L http://getcomposer.org/composer.phar > composer.phar
md5 composer.phar > composer.phar.md5

mkdir composer
mv composer.phar composer
mv composer.phar.md5 composer

swift_upload "composer/composer.phar"
swift_upload "composer/composer.phar.md5"
