#!/usr/bin/env bash

set -e

if [ -n "$DEBUG" ]; then
    set -x
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"
source "$basedir/lib/utils"
source "$basedir/lib/swift"

validate_env

package="$1"

cd $(mktmpdir swift)

echo "-----> Creating checksum for ${package}"

swift_download "package/${package}.tgz"

[ -d "./package" ] && rm -r ./package
mv "${STACK}/package" "package"

md5 "package/${package}.tgz" > "package/${package}.md5"
swift_upload "package/${package}.md5"
