#!/usr/bin/env bash

set -e

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"
source "$basedir/utils"
source "$basedir/swift"

validate_env

package="$1"

cd $(mktmpdir swift)

echo "-----> Creating checksum for ${package}"

swift_download "package/${package}.tgz"

md5 "package/${package}.tgz" > "package/${package}.md5"
swift_upload "package/${package}.md5"
