#!/usr/bin/env bash

set -e

if [ -n "$DEBUG" ]; then
  set -x
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"
source "$basedir/lib/utils"
source "$basedir/lib/swift"

export PATH=${basedir}/../vendor/bin:$PATH

if [ -z "$1" ]; then
    echo "Usage: $0 <version>" >&2
    exit 1
fi

php_version="$1"

echo "-----> Packaging PHP $php_version"

tempdir=$(mktmpdir php)
cd "$tempdir"

echo "-----> Downloading dependency zlib ${zlib_version}"
curl -LO "${PHP_BASE_URL}/zlib/zlib-${zlib_version}.tar.gz"
tar -xzf "zlib-${zlib_version}.tar.gz"

echo "-----> Downloading dependency libonig ${libonig_version}"
mkdir /app/vendor/libonig -p
curl -L -o - "${PHP_BASE_URL}/package/libonig-${libonig_version}.tgz" | tar -C /app/vendor/libonig -xvz
export C_INCLUDE_PATH="$C_INCLUDE_PATH:/app/vendor/libonig/include"
export PKG_CONFIG_PATH="/app/vendor/libonig/lib/pkgconfig:$PKG_CONFIG_PATH"

echo "-----> Downloading dependency WebP library ${webp_version}"
mkdir -p "/app/vendor/libwebp"
curl "${PHP_BASE_URL}/package/libwebp-${webp_version}.tgz" | tar xz -C /app/vendor/libwebp

echo "-----> Downloading PHP $php_version"
curl -LO "https://php.net/distributions/php-${php_version}.tar.gz"
tar -xzf "php-${php_version}.tar.gz"

install_zend_optimizer=":"
install_zend_optimizer=$(cat <<SH
    echo "zend_extension=opcache.so" > /app/vendor/php/etc/conf.d/opcache.ini
SH
)

WITH_CURL_CONFIGURE="--with-curl=/usr"
if [ -d '/app/.apt/usr' ] ; then
    WITH_CURL_CONFIGURE="--with-curl=/app/.apt/usr"
fi

export WEBP_LIBS="-L/app/vendor/libwebp/lib -lwebp"
export WEBP_CFLAGS="-I/app/vendor/libwebp/include"

mkdir -p "/app/vendor/php/etc/conf.d"

echo "-----> Compile ZLib v${zlib_version}"
pushd "zlib-${zlib_version}" >/dev/null
./configure --prefix=/app/vendor/php/zlib
make
make install
popd > /dev/null

echo "-----> Compile PHP v${php_version}"
pushd "php-${php_version}" >/dev/null
./configure --prefix=/app/vendor/php \
  --with-config-file-path=/app/vendor/php/etc \
  --with-config-file-scan-dir=/app/vendor/php/etc/conf.d \
  --enable-intl \
  --enable-gd --with-jpeg --with-freetype --with-webp \
  --enable-exif \
  --with-mysqli \
  --with-pdo-mysql \
  --with-pdo-sqlite \
  --with-pdo-pgsql=/usr/bin/pg_config \
  --with-pgsql \
  --enable-shmop \
  --with-zip \
  ${WITH_CURL_CONFIGURE} \
  --with-zlib=/app/vendor/php/zlib \
  --with-bz2 \
  --with-openssl \
  --enable-soap \
  --enable-xmlreader \
  --with-xsl \
  --enable-fpm \
  --enable-mbstring \
  --enable-pcntl \
  --enable-sockets \
  --enable-bcmath \
  --with-readline \
  --with-password-argon2 \
  --disable-debug
echo "${php_version}" | grep ^5.3 && sed -i '/^BUILD_/ s/\$(CC)/\$(CXX)/g' Makefile || true
make -j 8
make install
popd > /dev/null

eval "$install_zend_optimizer"

mkdir package
pushd /app/vendor/php > /dev/null
tar zcf "${tempdir}/package/php-${php_version}.tgz" .
popd > /dev/null

echo "-----> Moving package to Swift"

swift_upload "package/php-${php_version}.tgz"

"$basedir/manifest" php
"$basedir/package-checksum" "php-${php_version}"

echo "-----> Done building PHP package!"
