#!/usr/bin/env bash

set -e

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"
source "$basedir/lib/utils"
source "$basedir/lib/swift"

export PATH=${basedir}/../vendor/bin:$PATH

validate_env

tempdir="$(mktmpdir libmemcached)"
cd $tempdir

echo "-----> Downloading libmemcached"

curl -LO "https://launchpad.net/libmemcached/1.0/${libmemcached_version}/+download/libmemcached-${libmemcached_version}.tar.gz"
tar -xzvf "libmemcached-${libmemcached_version}.tar.gz"

pushd libmemcached-${libmemcached_version} >/dev/null && \
    mkdir -p /app/vendor/libmemcached && \
    ./configure --with-memcached=no --prefix=/app/vendor/libmemcached && \
    make CXXFLAGS="-fpermissive" && make install && popd > /dev/null

rm -r /app/vendor/libmemcached/share/man

mkdir package
pushd /app/vendor/libmemcached
tar zcvf ${tempdir}/package/libmemcached-${libmemcached_version}.tgz .
popd

echo "-----> Uploading package to Swift"
swift_upload package/libmemcached-${libmemcached_version}.tgz

"$basedir/package-checksum" libmemcached-${libmemcached_version}

echo "-----> Done building libmemcached package!"
