#!/usr/bin/env bash

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"
source "$basedir/lib/utils"
source "$basedir/lib/swift"

tempdir=$(mktmpdir jq)
cd $tempdir

echo "----> Vendoring 'jq'"
curl -L https://stedolan.github.io/jq/download/linux64/jq > jq_bin

mkdir jq
mv jq_bin jq/jq
swift_upload jq/jq
