#!/usr/bin/env bash

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

source "$basedir/../conf/buildpack.conf"
source "$basedir/lib/utils"
source "$basedir/lib/swift"


pushd $basedir/reader
go build .
popd

swift_upload reader/reader
rm reader/reader
