#!/usr/bin/env bash
#
# This script is used for the [Nginx
# buildpack](github.com/Scalingo/nginx-buildpack/). Please refer to this page
# (https://www.notion.so/scalingooriginal/New-Nginx-Version-936b92e173a74f5ab0cd59e5155a4880)
# on how to use it.
#

set -e

nginx_version="$1"

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"
source "$basedir/lib/utils"
source "$basedir/lib/swift"

validate_env

export PATH=${basedir}/../vendor/bin:$PATH

if [ -z "$nginx_version" ]; then
  echo "Usage: $0 <version>" >&2
  exit $E_ARG_MISSING
fi

if [ -z "$NGINX_ZLIB_VERSION" ]; then
  NGINX_ZLIB_VERSION=1.2.11
fi

if [ -z "$NGINX_PCRE_VERSION" ]; then
  # From https://sourceforge.net/projects/pcre/files/pcre/
  NGINX_PCRE_VERSION=8.43
fi

zlib_version="$NGINX_ZLIB_VERSION"
pcre_version="$NGINX_PCRE_VERSION"

tempdir=$(mktmpdir nginx)
cd $tempdir

echo "-----> Downloading dependency PCRE ${pcre_version}"

curl -LO "https://sourceforge.net/projects/pcre/files/pcre/${pcre_version}/pcre-${pcre_version}.tar.gz"
tar -xzvf "pcre-${pcre_version}.tar.gz"

echo "-----> Downloading dependency zlib ${zlib_version}"

curl -LO "${SWIFT_URL}/zlib/zlib-${zlib_version}.tar.gz"
tar -xzvf "zlib-${zlib_version}.tar.gz"

echo "-----> Downloading NGINX ${nginx_version}"

curl -LO "https://nginx.org/download/nginx-${nginx_version}.tar.gz"
tar -xzvf "nginx-${nginx_version}.tar.gz"

echo "-----> Uploading source to build server"

pushd nginx-${nginx_version} >/dev/null && \
  ./configure \
    --prefix=/app/vendor/nginx \
    --with-http_ssl_module \
    --with-pcre=../pcre-${pcre_version} \
    --with-zlib=../zlib-${zlib_version} \
    --with-http_realip_module && \
  make && make install && \
  popd > /dev/null

echo "-----> Uploading package to Swift ${SWIFT_URL}/package/nginx-${nginx_version}.tgz"

mkdir package
pushd /app/vendor/nginx >/dev/null
tar zcvf "${tempdir}/package/nginx-${nginx_version}.tgz" .
popd >/dev/null

swift_upload package/nginx-${nginx_version}.tgz
"$basedir/manifest" nginx
"$basedir/package-checksum" "nginx-${nginx_version}"

echo "-----> Done building Nginx package!"
