#!/usr/bin/env bash
#
# Package all extensions: both internal and non-internal.

if [ -n "$DEBUG" ]; then
    set -x
fi

if [ -z "$1" ]; then
    echo "Usage: $0 PHP_VERSION"
    echo "Example: $0 7.4"
    exit 1
fi

set -e
set -o pipefail

php_version=$1

cd $( cd -P "$( dirname "$0" )" && pwd )

for e in ./ext-internal/*; do
  ext_name="$( basename "${e}" )"

  ./package_internal_ext "${ext_name}" "${php_version}"

  if [[ $? -ne 0 ]]; then
    echo "Error packaging internal extension ${ext_name}"
    exit -1
  fi
done

for e in ./ext/*; do
  ext_name="$( basename "${e}" )"

  ./package_ext "${ext_name}" "${ext_name}" "${php_version}"

  if [[ $? -ne 0 ]]; then
    echo "Error packaging extension ${ext_name}"
    exit -1
  fi
done
