#!/usr/bin/env bash

set -e

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"
source "$basedir/utils"
source "$basedir/swift"

export PATH=${basedir}/../vendor/bin:$PATH

validate_env

tempdir="$(mktmpdir libmemcached)"
cd $tempdir

memcached_version=1.0.18

echo "-----> Downloading libmemcached"

curl -LO "https://launchpad.net/libmemcached/1.0/${memcached_version}/+download/libmemcached-${memcached_version}.tar.gz"
tar -xzvf "libmemcached-${memcached_version}.tar.gz"

cd libmemcached-${memcached_version} && \
    mkdir -p /app/vendor/libmemcached && \
    ./configure --with-memcached=no --prefix=/app/vendor/libmemcached && \
    make && make install

rm -r /app/vendor/libmemcached/share/man

mkdir package
tar zcvf package/libmemcached-${memcached_version}.tgz /app/vendor/libmemcached

echo "-----> Uploading package to Swift"
swift_upload package/libmemcached-${memcached_version}.tgz

"$basedir/package-checksum" libmemcached-${memcached_version}

echo "-----> Done building libmemcached package!"
