#!/usr/bin/env bash

which jq 2>/dev/null || (apt-get update && apt-get install -y jq) 

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"
source "$basedir/lib/utils"
source "$basedir/lib/swift"

tempdir=$(mktmpdir composer)
cd $tempdir

BASE_COMPOSER_URL="https://getcomposer.org/"

current_composer_version_path=$(curl --silent "$BASE_COMPOSER_URL/versions" | jq -r '.stable[0].path')

curl -L "$BASE_COMPOSER_URL/$current_composer_version_path" > composer.phar
md5 composer.phar > composer.phar.md5

mkdir composer
mv composer.phar composer
mv composer.phar.md5 composer

swift_upload "composer/composer.phar"
swift_upload "composer/composer.phar.md5"
