#!/bin/bash

BUILD_DIR="$2"
basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source $basedir/../bin/common.sh

function requires_change4() {
  require_change=$(jq --raw-output ".require[\"rbschange/core\"] // \"\"" < "$BUILD_DIR/composer.json")
  [ -n  "$require_change" ]
}

case "$1" in
    detect)
        if [ ! -f "$BUILD_DIR/composer.json" ]; then
            exit 1
        fi

        if requires_change4; then
            echo "-----> Detected Change 4 app"
            exit 0
        else
            exit 1
        fi
        ;;
    get-log-files)
        echo "log/project/application.log"
        ;;
    compile)
        echo "-----> Setting up Change 4 app"
        cp "$basedir/../conf/nginx/change4.conf.erb" "$BUILD_DIR/conf/site.conf.erb"
        ;;
    end)
        echo "-----> Bootstrap Change 4 base plugins"
        php bin/change.phar change:generate-db-schema | indent
        php bin/change.phar change:register-plugin --all | indent
        php bin/change.phar change:install-package --vendor=Rbs Core | indent
        php bin/change.phar change:install-package --vendor=Rbs ECom | indent
        php bin/change.phar change:install-plugin --type=theme --vendor=Rbs Demo | indent

        echo "-----> Change references to build directory"
        for php_file in $BUILD_DIR/www/*.php ; do
          sed -i 's+/build+/app+g' $php_file
        done
        ;;
esac
