#!/bin/bash

BUILD_DIR="$2"
basedir="$( cd -P "$( dirname "$0" )" && pwd )"

function requires_lumen() {
    jq --raw-output '.packages | .[] | .name' < "$BUILD_DIR/composer.lock" | grep -q '^laravel/lumen-framework$'
}

function sets_framework_lumen() {
    [ "$(jq --raw-output '.extra.heroku.framework' < "$BUILD_DIR/composer.json")" == "lumen" ]
}

case "$1" in
    detect)
        if [ ! -f "$BUILD_DIR/composer.lock" ]; then
            exit 1
        fi

        if requires_lumen|| sets_framework_lumen; then
            echo "-----> Detected Lumen app"
            exit 0
        else
            exit 1
        fi
        ;;
    compile)
        echo "-----> Setting up Lumen app"
        cp "$basedir/../conf/nginx/lumen.conf.erb" "$BUILD_DIR/conf/site.conf.erb"
        ;;
esac
