#!/bin/bash

BUILD_DIR="$2"
basedir="$( cd -P "$( dirname "$0" )" && pwd )"

case "$1" in
    detect)
        if [ -f "$BUILD_DIR/app/Mage.php" ]; then
            echo "-----> Detected Magento app"
            exit 0
        else
            exit 1
        fi
        ;;
    compile)
        echo "-----> Setting up Magento app"
        cp "$basedir/../conf/nginx/magento.conf.erb" "$BUILD_DIR/conf/site.conf.erb"
        ;;
esac
