dependencies = []
description = "Official Scalingo PHP buildpack"
destination_server = []
flags = ["buildpack"]
languages = ["shell", "github-actions"]
owner = "team-infrastructure-services@scalingo.com"
team = "IST"
tier = 1
version = "1.0.0"
