#!/usr/bin/env bash

set -e

if [ -n "$DEBUG" ]; then
    set -x
fi

mongo_version="1.6.16"

curl -L "https://github.com/mongodb/mongo-php-driver-legacy/archive/${mongo_version}.tar.gz" \
    | tar xzv

cd mongo-php-driver-legacy-${mongo_version}
/app/vendor/php/bin/phpize
./configure --with-php-config=/app/vendor/php/bin/php-config \
            --enable-mongo

make
cp modules/mongo.so "$EXT_DIR/mongo.so"
echo "extension=mongo.so" > "$PREFIX/etc/conf.d/mongo.ini"
