#!/bin/bash

php_version=$1
zend_api_version=$2
php_src_dir=$3

pushd $php_src_dir/php-${php_version}/ext/calendar

export PATH=$PATH:/app/vendor/php/bin

phpize
./configure --with-calendar
make
make install

cp modules/calendar.so "$EXT_DIR"
popd

echo "extension=calendar.so" > "$PREFIX/etc/conf.d/calendar.ini"
