#!/bin/bash

set -e

if [ -n "$DEBUG" ]; then
    set -x
fi

php_version=$1
zend_api_version=$2
php_src_dir=$3

if [ ! -d /app/vendor/libc-client ] ; then
  /buildpack/support/get_libc_client
fi

# This is now required starting with PHP 7.4.0
export PHP_OPENSSL=yes

pushd $php_src_dir/php-${php_version}/ext/imap

export PATH=$PATH:/app/vendor/php/bin

phpize
./configure --with-imap=/app/vendor/libc-client --with-imap-ssl
make
make install

cp modules/imap.so "$EXT_DIR"
popd

echo "extension=imap.so" > "$PREFIX/etc/conf.d/imap.ini"
