#!/bin/bash

set -e

php_version=$1
zend_api_version=$2
php_src_dir=$3

tidy_version="5.6.0"

tidy_package="${SWIFT_URL}/package/libtidy-${tidy_version}.tgz"

curl -L "$tidy_package" > /tmp/tidy-${tidy_version}.tgz

mkdir -p /app/vendor/libtidy
tar -xzv -C /app/vendor/libtidy -f /tmp/tidy-${tidy_version}.tgz

pushd $php_src_dir/php-${php_version}/ext/tidy
export PATH=$PATH:/app/vendor/php/bin

phpize
./configure --with-tidy=/app/vendor/libtidy
make
make install

cp modules/tidy.so "$EXT_DIR"
popd

echo "extension=tidy.so" > "$PREFIX/etc/conf.d/tidy.ini"

