#!/bin/bash
#
# Compile the Tidy PHP extension (https://www.php.net/manual/en/book.tidy.php). The outcome is a .so file that is uploaded to the object storage. This file is downloaded during the deployment if a customer enables the Tidy extension.
#

set -e

if [ -n "$DEBUG" ]; then
  set -x
fi

php_version=$1
zend_api_version=$2
php_src_dir=$3

source "/buildpack/conf/versions.sh"
tidy_package="${PHP_BASE_URL}/package/libtidy-${libtidy_version}.tgz"

curl --location "$tidy_package" > /tmp/tidy-${libtidy_version}.tgz

mkdir --parents /app/vendor/libtidy
tar --extract --gzip --directory=/app/vendor/libtidy --file=/tmp/tidy-${libtidy_version}.tgz

pushd $php_src_dir/php-${php_version}/ext/tidy
export PATH=$PATH:/app/vendor/php/bin

phpize
./configure --with-tidy=/app/vendor/libtidy
make
make install

cp modules/tidy.so "$EXT_DIR"
popd

echo "extension=tidy.so" > "$PREFIX/etc/conf.d/tidy.ini"
