#!/usr/bin/env bash

set -e

php_version=${1:=7.4}

if echo $php_version | grep -q -E '^[78].' ; then
  apcu_version=5.1.19
else
  apcu_version=4.0.11
fi

curl -L "https://pecl.php.net/get/apcu-${apcu_version}.tgz" \
    | tar xzv

cd apcu-${apcu_version}
/app/vendor/php/bin/phpize
./configure --with-php-config=/app/vendor/php/bin/php-config

make
cp modules/apcu.so "$EXT_DIR/apcu.so"
echo "extension=apcu.so" > "$PREFIX/etc/conf.d/apcu.ini"
