#!/usr/bin/env bash

set -e

if [ -n "$DEBUG" ]; then
    set -x
fi

php_version=${1:=8.2}

# $apcu_version, $PREFIX and $EXT_DIR are loaded from buildpack.conf
source "/buildpack/conf/buildpack.conf"

curl --location "https://pecl.php.net/get/apcu-${apcu_version}.tgz" \
    | tar --extract --gzip --verbose

cd apcu-${apcu_version}
/app/vendor/php/bin/phpize
./configure --with-php-config=/app/vendor/php/bin/php-config

make
cp modules/apcu.so "$EXT_DIR/apcu.so"
echo "extension=apcu.so" > "$PREFIX/etc/conf.d/apcu.ini"
