#!/usr/bin/env bash

set -e

if [ -n "$DEBUG" ]; then
    set -x
fi

php_version=${1:=8.2}
ds_version=1.4.0

curl -L "https://pecl.php.net/get/ds-${ds_version}.tgz" \
    | tar xzv

cd ds-${ds_version}
/app/vendor/php/bin/phpize
./configure --with-php-config=/app/vendor/php/bin/php-config

make
cp modules/ds.so "$EXT_DIR/ds.so"
echo "extension=ds.so" > "$PREFIX/etc/conf.d/ds.ini"
