#!/usr/bin/env bash

set -e

if [ -n "$DEBUG" ]; then
    set -x
fi

php_version=${1:=8.2}

event_version="3.0.8"

# libwebp is required to compile this library starting with scalingo-20
if [[ ! -d /app/vendor/libwebp ]]; then
  /buildpack/support/get_webp
fi

curl --location \
  "https://pecl.php.net/get/event-${event_version}.tgz" \
  | tar -xzv

pushd event-${event_version}

/app/vendor/php/bin/phpize
./configure --with-php-config=/app/vendor/php/bin/php-config

make
cp modules/event.so "$EXT_DIR/event.so"

popd

echo "extension=event.so" > "$PREFIX/etc/conf.d/event.ini"
