#!/usr/bin/env bash

set -e

if [ -n "$DEBUG" ]; then
    set -x
fi

# $igbinary_version, $PREFIX and $EXT_DIR are loaded from versions.sh
source "/buildpack/conf/versions.sh"

curl --location "https://github.com/igbinary/igbinary/archive/${igbinary_version}.tar.gz" \
    | tar xzv

pushd "igbinary-${igbinary_version}"

/app/vendor/php/bin/phpize
./configure --with-php-config=/app/vendor/php/bin/php-config \
            --enable-igbinary

make
cp modules/igbinary.so "${EXT_DIR}/igbinary.so"

popd

echo "extension=igbinary.so" > "${PREFIX}/etc/conf.d/igbinary.ini"
