#!/usr/bin/env bash

set -e

if [ -n "$DEBUG" ]; then
    set -x
fi

php_version=${1:=8.2}

mcrypt_version=1.0.9

curl -L "https://pecl.php.net/get/mcrypt-${mcrypt_version}.tgz" \
    | tar xzv

cd mcrypt-${mcrypt_version}
/app/vendor/php/bin/phpize
./configure --with-php-config=/app/vendor/php/bin/php-config

make
cp modules/mcrypt.so "$EXT_DIR/mcrypt.so"
echo "extension=mcrypt.so" > "$PREFIX/etc/conf.d/mcrypt.ini"
