#!/usr/bin/env bash

set -e

# https://github.com/php-memcached-dev/php-memcached/releases
php_memcached_version=3.1.5

curl -L "https://github.com/php-memcached-dev/php-memcached/archive/v${php_memcached_version}.tar.gz" \
    | tar xzv

# https://packages.debian.org/buster/libmemcached-dev
mkdir -p /app/vendor/libmemcached
curl "${SWIFT_URL}/package/libmemcached-1.0.18.tgz" \
    | tar xzv -C /app/vendor/libmemcached

cd php-memcached-${php_memcached_version}
/app/vendor/php/bin/phpize
./configure --with-php-config=/app/vendor/php/bin/php-config \
            --disable-memcached-sasl \
            --with-libmemcached-dir=/app/vendor/libmemcached \
            --enable-memcached

make
cp modules/memcached.so "$EXT_DIR/memcached.so"
echo "extension=memcached.so" > "$PREFIX/etc/conf.d/memcached.ini"
