#!/usr/bin/env bash

set -e

if [ -n "$DEBUG" ]; then
    set -x
fi

# $memcached_version, $libmemcached_version, $PREFIX and $EXT_DIR are loaded from versions.sh
source "/buildpack/conf/versions.sh"

curl --location "https://github.com/php-memcached-dev/php-memcached/archive/v${memcached_version}.tar.gz" \
    | tar --extract --gzip --verbose

mkdir -p /app/vendor/libmemcached
curl "${PHP_BASE_URL}/package/libmemcached-${libmemcached_version}.tgz" \
    | tar --extract --gzip --verbose --directory=/app/vendor/libmemcached

cd php-memcached-${memcached_version}
/app/vendor/php/bin/phpize
./configure --with-php-config=/app/vendor/php/bin/php-config \
            --disable-memcached-sasl \
            --with-libmemcached-dir=/app/vendor/libmemcached \
            --enable-memcached

make
cp modules/memcached.so "$EXT_DIR/memcached.so"
echo "extension=memcached.so" > "$PREFIX/etc/conf.d/memcached.ini"
