#!/usr/bin/env bash

php_memcache_version=3.0.8

curl -L "https://github.com/php/pecl-caching-memcache/archive/memcache-${php_memcache_version}.tar.gz" \
    | tar xzv

cd pecl-caching-memcache-memcache-${php_memcache_version}
/app/vendor/php/bin/phpize
./configure --with-php-config=/app/vendor/php/bin/php-config

make
cp modules/memcache.so "$EXT_DIR/memcache.so"
echo "extension=memcache.so" > "$PREFIX/etc/conf.d/memcache.ini"
