#!/usr/bin/env bash

set -e

if [ -n "$DEBUG" ]; then
    set -x
fi

# https://github.com/php-memcached-dev/php-memcached/releases
php_memcached_version=3.2.0

curl -L "https://github.com/php-memcached-dev/php-memcached/archive/v${php_memcached_version}.tar.gz" \
    | tar xzv

source "/buildpack/conf/buildpack.conf"
mkdir -p /app/vendor/libmemcached
curl "${PHP_BASE_URL}/package/libmemcached-${libmemcached_version}.tgz" \
    | tar xzv -C /app/vendor/libmemcached

cd php-memcached-${php_memcached_version}
/app/vendor/php/bin/phpize
./configure --with-php-config=/app/vendor/php/bin/php-config \
            --disable-memcached-sasl \
            --with-libmemcached-dir=/app/vendor/libmemcached \
            --enable-memcached

make
cp modules/memcached.so "$EXT_DIR/memcached.so"
echo "extension=memcached.so" > "$PREFIX/etc/conf.d/memcached.ini"
