#!/usr/bin/env bash

set -e

phalcon_version="3.4.5"

curl --location \
  "https://github.com/phalcon/cphalcon/archive/v${phalcon_version}.tar.gz" \
  | tar -xzv

cd cphalcon-${phalcon_version}/build

export PATH=$PATH:/app/vendor/php/bin

./install

cp php7/64bits/modules/phalcon.so "$EXT_DIR/phalcon.so"
echo "extension=phalcon.so" > "$PREFIX/etc/conf.d/phalcon.ini"
