#!/usr/bin/env bash

set -e

if [ -n "$DEBUG" ]; then
    set -x
fi

# $phpredis_version, $PREFIX and $EXT_DIR are loaded from buildpack.conf
source "/buildpack/conf/buildpack.conf"

url="https://github.com/phpredis/phpredis/archive/refs/tags/${phpredis_version}.tar.gz"

curl --location "${url}" \
    | tar -xzv

pushd phpredis-${phpredis_version}

/app/vendor/php/bin/phpize ; rc=$?

if [ $rc -ne 0 ] ; then
    echo "Fail to PHPize phpredis extension"
    exit 1
fi

./configure \
    --with-php-config=/app/vendor/php/bin/php-config \
    --enable-redis ; rc=$?

if [ $rc -ne 0  ] ; then
    echo "Fail to configure phpredis extension"
    exit 1
fi

make ; rc=$?

if [ $rc -ne 0 ] ; then
    echo "Fail to build phpredis extension"
    exit 1
fi

cp modules/redis.so "${EXT_DIR}/redis.so"

popd

echo "extension=redis.so" > "${PREFIX}/etc/conf.d/redis.ini"
