---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  unit-tests:
    name: "Unit Tests (${{ matrix.stack }})"
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        stack:
          - scalingo-22
          - scalingo-24
    container:
      image: "scalingo/${{ matrix.stack }}:latest"
      env:
        STACK: "${{ matrix.stack }}"
    steps:
      - name: 🛎  Checkout
        uses: actions/checkout@v6

      - name: 🔎 Run tests
        run: |
          test/run
...
